name: "Publish PowerShell Module To NuGet"
description: "Reusable action to build, tag, validate, and publish a PowerShell module to the PowerShell Gallery."
author: "itmvha"

branding:
  icon: 'package'  # Options include 'package', 'code', 'gear', 'cloud', etc.
  color: 'blue'    # Supported colors include 'blue', 'green', 'purple', 'red', 'yellow', or a hex code (e.g., '#0366d6')

inputs:
  psd1Path:
    description: "Path to the PSD1 manifest file."
    required: true
  psm1Path:
    description: "Path to the PSM1 module file."
    required: true
  companyName:
    description: "The name of the company required by nuget"
    required: true
  apiKey:
    description: "NuGet API key for publishing to the PowerShell Gallery."
    required: true
    secret: true
  rootModule:
    description: "the name of the module."
    required: true
  description:
    description: "the description for the module."
    required: true

runs:
  using: "composite"
  steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    # Step 2: Tag with GitVersion
    - name: Tag with GitVersion
      id: gitversion
      uses: MKTHEPLUGG/gitversion-tag-action@v6
      with:
        configFilePath: gitversion.yml

    # Step 3: Get commit message
    - name: Get commit message
      id: commitMessage
      run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
      shell: bash

    # Step 4: Create module manifest
    - name: Create module manifest
      run: |
        New-ModuleManifest -Path "${{ inputs.psd1Path }}" `
        -RootModule "${{ inputs.rootModule }}" `
        -FunctionsToExport '*' `
        -Author "itmvha" -ModuleVersion "${{ steps.gitversion.outputs.semVer }}" `
        -Description "${{ inputs.description }}" `
        -CompanyName "${{ inputs.companyName }}" `
        -ReleaseNotes "$env:message"
      shell: powershell

    # Step Debug: Check if files needed for module creation were succesfully found.
#    - name: Debug previous steps
#      run: |
#        if (Test-Path "${{ inputs.psd1Path }}") {
#        Write-Host "PDS.psd1 manifest created successfully."
#        } else {
#          Write-Error "Failed to create PDS.psd1 manifest at expected path."
#        }
#          if (Test-Path "${{ inputs.psm1Path }}") {
#          Write-Host "PDS.psm1 manifest has been found."
#        } else {
#          Write-Error "Failed to find PDS.psm1 manifest at expected path."
#        }
#      shell: powershell

    # Step 5: Test module manifest
    - name: Test module manifest
      run: |
        Test-ModuleManifest -Path "${{ inputs.psd1Path }}"
      shell: powershell

    # Step 6: Publish PowerShell module
    - name: Publish to PowerShell Gallery
      run: |
        Publish-Module -Name "${{ inputs.psm1Path }}" -NuGetApiKey "${{ inputs.apiKey }}"
      shell: powershell
